### ISSUE TITLE
dash Cache has no `get_with`

### ISSUE THREAD

**Issue by gitmalong** [moka-rs/moka#168]
or am I missing something?
Edit: Noticed there is `get_or_insert_with`

**Comment by tatsuya6502** [comment]
Hi. You are right; `dash::Cache` has no `get_with` (or `get_or_insert_with`).

A bit of history; we added the experimental `dash::Cache` for the following reasons:

1. A user wanted to ensure never to get an issue: #34
    - The segmentation fault was occurring in our concurrent lock-free hash table implementation `moka::cht`. 
    - `moka::cht` is used by `sync` and `future` caches.
2. The same user wanted to reduce external crate dependencies. e.g. Remove crossbeam-epoch crate that is used by `moka::cht`.

We used `dashmap::DashMap` as an alternative concurrent hash table. However, implementing `get_with` method on it would require a non trivial amount of work, so we decided not to do it.

Now Moka [v0.9.2](https://crates.io/crates/moka/0.9.2) was just released with the fix for issue #34. So if you wanted to use `dash::Cache` just because to avoid the issue, you no longer have to use it. If so, please use `sync::Cache` or `future::Cache` instead.

**Comment by tatsuya6502** [comment]
I am closing this. Feel free to reopen if you find `sync::Cache` or `future::Cache` do not meet your requirements.
