### ISSUE TITLE
Eviction listener not always called.

### ISSUE THREAD

**Issue by peter-scholtens** [moka-rs/moka#266]
I tried a small example to trigger all use-cases of the eviction listener, but I see some unexpected behavior. The example looks like this:
```
use moka::sync::Cache;
use std::thread::sleep;
use std::time::Duration;

fn main() {
    // Make an artifically small cache and 1-second ttl to observe eviction listener.
    {
        let cache = Cache::builder()
            .max_capacity(2)
            .time_to_live(Duration::from_secs(1))
            .eviction_listener(|key, value, cause| {
                println!("Evicted ({:?},{:?}) because {:?}", key, value, cause)
            })
            .build();
        cache.insert(&0, "zero".to_string());
        cache.insert(&1, "one".to_string());
        cache.insert(&2, "two".to_string());
        sleep(Duration::from_secs(2));
        println!("Wake up!");
        cache.insert(&3, "three".to_string());
        cache.insert(&4, "four".to_string());
        cache.insert(&5, "five".to_string());
        let _ = cache.remove(&3);
        cache.invalidate(&4);
        cache.invalidate_all();
        cache.insert(&6, "six".to_string());
        println!("Cache structure removed.");
    }
    sleep(Duration::from_secs(1));
    println!("Exit program.");
}
```
Keys 0 till 4 get evicted for _Size_, _Expired_ or _Explicit_, so these are okay, however:
- I would expect key 5 to be evicted for the same reason as key 4 due to `invalidate_all()`, but nothing is reported.
- And key 6 is destroyed with the cache when the **cache structure is destroyed**, so also there I would expect _Explicit_

For a cache of webserver holding sessions, I want to use the eviction listener to clean-up other memory stuff too, holding e.g. user data. So it must be report all evictions otherwise memory leaks.

**Comment by tatsuya6502** [comment]
Hi. Thank you for reporting.

These key 5 and 6 issues are expected in the current version of Moka (v0.11.0). You can workaround by adding the following codes to your program:

```rust
// Before dropping the cache, call `invalidate_all()` and then call
// `sync()` repeatedly until the entry count becomes zero.

// This trait provides the `sync()` method:
use moka::sync::ConcurrentCacheExt;

cache.invalidate_all();
loop {
    // Run pending maintenance tasks. Single `sync()` call can remove
    // up to 500 invalidated entries and 500 expired entries. The eviction
    // listener is called for each removed entry.
    cache.sync();

    // Check if we are done.
    //
    // Note that `entry_count()` may return a wrong value if we do not call
    // `sync()` first. See the documentation for details:
    // https://docs.rs/moka/0.11.0/moka/sync/struct.Cache.html#method.entry_count
    if cache.entry_count() == 0 {
        break;
    }
}
```

Here are the details.

> And key 6 is destroyed with the cache when the **cache structure is destroyed**, so also there I would expect _Explicit_

It is not documented but the current `drop` implementation does not call the eviction listener for the dropped entries.

https://github.com/moka-rs/moka/blob/v0.11.0/src/notification.rs#L13-L14

```rust
// NOTE: Currently, dropping the cache will drop all entries without sending
// notifications. Calling `invalidate_all` method of the cache will trigger
// the notifications, ...
```

I will update the documentation.

> I would expect key 5 to be evicted for the same reason as key 4 due to `invalidate_all()`, but nothing is reported.

There will be some delay until key 5 is evicted. This is because `invalidate_all()` does not remove the entries immediately; cache has a housekeeping thread that removes the entries periodically. The eviction listener is called when the entries are removed.

https://docs.rs/moka/0.11.0/moka/sync/struct.Cache.html#method.invalidate_all

> This method returns immediately and a background thread will evict all the cached values inserted before the time when this method was called.

Under normal loads, the housekeeping thread runs every 300 milliseconds, and removes the entries that are expired or invalidated by `invalidate_all()`. There are max numbers of entries that can be removed in a single housekeeping run. If the number of entries to be removed exceeds the max numbers, the housekeeping thread will remove the remaining entries in the next run.

https://github.com/moka-rs/moka/blob/v0.11.0/src/sync_base/base_cache.rs#L1312-L1315

```rust
mod batch_size {
    pub(crate) const EVICTION_BATCH_SIZE: usize = 500;
    pub(crate) const INVALIDATION_BATCH_SIZE: usize = 500;
}
```

You can call the `sync()` method of `moka::sync::ConcurrentCacheExt` to run the housekeeping task immediately.
