### ISSUE TITLE
Reason for `Arc<Error>`

### ISSUE THREAD

**Issue by Palmik** [moka-rs/moka#328]
Hi, I was wondering why e.g. `try_get_with` and other similar methods return `Result<T, Arc<E>>` rather than `Result<T, E>`?

**Comment by tatsuya6502** [comment]
Hi. That is because `try_get_with` and other similar methods can return the same instance of error to more than one concurrent callers.

https://docs.rs/moka/0.12.0/moka/sync/struct.Cache.html#method.try_get_with

> **Concurrent calls on the same key**
>
> This method guarantees that concurrent calls on the same not-existing key are coalesced into one evaluation of the `init` closure (as long as these closures return the same error type). Only one of the calls evaluates its closure, and other calls wait for that closure to complete.

The following code will demonstrate this behavior:

```rust
// Cargo.toml
//
// [dependencies]
// moka = { version = "0.12.0", features = ["sync"] }
// anyhow = "1.0.75"

use std::sync::{Arc, Barrier};

use moka::sync::Cache;

fn main() {
    const NUM_THREADS: usize = 4;

    let cache: Cache<&str, i32> = Cache::builder().build();
    let barrier = Arc::new(Barrier::new(NUM_THREADS));

    let threads = (0..NUM_THREADS)
        .map(|id| {
            let cache = cache.clone();
            let barrier = Arc::clone(&barrier);

            // Spawn a thread.
            std::thread::spawn(move || {
                // Wait for all threads to be ready.
                barrier.wait();

                println!("thread {} - started", id);

                // Try to insert and get the value from the cache.
                let result = cache.try_get_with("key", || {
                    println!("thread {} - calling the init closure", id);
                    std::thread::sleep(std::time::Duration::from_secs(3));
                    let err = anyhow::anyhow!("error from thread {}", id);
                    println!(
                        r#"thread {} - the init closure is returning error: "{:?}""#,
                        id, err
                    );
                    Err(err)
                });

                // Print the result.
                match result {
                    Ok(_) => unreachable!(),
                    Err(e) => println!("thread {} - got error: {:?}", id, e),
                }
            })
        })
        .collect::<Vec<_>>();

    // Wait for all threads to finish.
    for t in threads {
        t.join().unwrap();
    }
}
```

```console
$ cargo run

thread 3 - started
thread 3 - calling the init closure
thread 2 - started
thread 1 - started
thread 0 - started
thread 3 - the init closure is returning error: "error from thread 3"
thread 3 - got error: error from thread 3
thread 2 - got error: error from thread 3
thread 1 - got error: error from thread 3
thread 0 - got error: error from thread 3
```

Thread 0 to 3 are calling `try_get_with` concurrently on the same key. Only thread 3 evaluates the `init` closure, and other threads wait for the completion of the closure. When thread 3's `init` closure returns the error, the same error is returned to all the callers.

If the return type of `try_get_with` is  `Result<V, E>`, then the error type `E` must implement `Clone` trait. However, Rust's error types usually do not implement `Clone` trait, so it will be inconvenient. Instead, it returns `Result<V, Arc<E>>`; wrapping `E` with `Arc` so that `E` does not need to implement `Clone` trait, and the same error instance can be shared between callers.

If you think it will be rare to have concurrent calls on the same key in your application, then you might want to use `Arc::into_inner` function to try to get the inner value from `Arc`:

https://doc.rust-lang.org/stable/std/sync/struct.Arc.html#method.into_inner

> Returns the inner value, if the `Arc` has exactly one strong reference.

Here is an example replacing the `match` expression to use `Arc::into_inner`:

```rust
                // Print the result.
                match result {
                    Ok(_) => unreachable!(),
                    Err(e) => {
                        if let Some(e) = Arc::into_inner(e) {
                            println!(r#"thread {} - got the inner error: "{:?}""#, id, e);
                        } else {
                            println!("thread {} - could not get the inner error", id);
                        }
                    }
                }
```

```console
$ cargo run

thread 3 - started
thread 2 - started
thread 1 - started
thread 0 - started
thread 3 - calling the init closure
thread 3 - the init closure is returning error: "error from thread 3"
thread 3 - could not get the inner error
thread 1 - could not get the inner error
thread 2 - got the inner error: "error from thread 3"
thread 0 - could not get the inner error
```

Thread 2 got the inner error, but other threads could not get the inner error because the `Arc` has more than one strong reference at the time.

**Comment by Palmik** [comment]
Ah, right, that makes total sense! I wonder if imposing "E: Clone" instead would give more flexibility, as it would allow the user to either wrap the error in Arc themselves, if needed.

Anyway, thanks for the answer!
