### ISSUE TITLE
Can Moka combine entries ?

### ISSUE THREAD

**Issue by lynn2910** [moka-rs/moka#353]
Hello,
I've just discovered this crate and I'm thinking of using it, but I haven't found any information about combining inputs.

To put it simply, for my project, I have data that is not complete, and depending on what I receive from the API, I can update the cache with fields that have changed or are non-existent.
Is this possible with Moka?

**Comment by tatsuya6502** [comment]
Sorry for a late reply.

Right, you can solve the problem by making an `Arc<Mutex<T>>` or `Arc<RwLock<T>>` of your data `T`. However there are some limitations on expiration, eviction listener and size-based eviction. This is because you are modifying cached value without calling any cache API so cache's internal data structures like the LRU queue and expiration timers cannot be updated. For more details of the limitations, see the lower part of [this issue comment](https://github.com/moka-rs/moka/issues/179#issuecomment-1245414227).

To remove such limitations, I am currently working on the following new feature:

- #370

You might want to use the `and_upsert_with` method, although you will still need to use `Arc<Mutex<T>>` or `Arc<RwLock<T>>`. For more details, see this example [append_value_async.rs](https://github.com/moka-rs/moka/blob/compute-api/examples/append_value_async.rs) in the pull request.

**Comment by tatsuya6502** [comment]
I am reviewing #370 now and will merge it today. I will publish moka `v0.12.3` hopefully in a few days.
