### ISSUE TITLE
Question about usage with channels to create a Stream like interface

### ISSUE THREAD

**Issue by Threated** [moka-rs/moka#377]
Hello, I am using the `moka::future::Cache` and a `tokio::sync::broadcast::channel` and I want to create a function which returns a `futures::Stream` of Items (all from the Cache and Streaming the new once via the channel).

The Problem is when do I subscribe to the channel? If I subscribe before iterating over the channel I might get duplicate Items which seems expensive to dedupe because I dont want to check for dupes for every new element. If I subscribe after storing all Cache Items in a Vec I might miss elements because another thread is inserting a new Element as I am iterating before I subscribe.
Is there an efficient way to do this?

PS: I know this is kind of not really related to moka but I thought someone here might know a good solution. If not feel free to close the issue

**Comment by tatsuya6502** [comment]
Hi. Thanks for using `moka`!

I am afraid I do not understand what you are trying to do. I am not sure how you are getting all items from the cache and why you will get duplicate items. Perhaps you can write some codes to explain?

Maybe you are asking for a way to get all cached items while other threads are inserting new items to the cache? Maybe you get duplicate items because you have to iterate the cache repeatedly until you catch up to all insertions?

**Comment by tatsuya6502** [comment]
As for deduplicating items (key-value pairs) in a stream, I think there are not much options.

Note that the followings assume that items are considered duplicates _only if_ their keys are the same. No need to check if their values are the same.

If you need 100% accuracy, that is to guarantee each unique key should appear exactly once, you will need to store keys in a collection such as `HashSet<Key>`.

- Every time you get an item, check if its key is a member of the set.
    - If yes, it is a duplicate key (= duplicate item) so discard it.
    - If not, it is a new key so add it to the set and use the item.
- Depending on the requirement, you will need to keep these keys in the set as long as your cache and broadcast channel live.
    - If you can remove keys after certain time elapsed, you might want to use a `future::Cache<Key, ()>` with only TTL (time-to-live) configured, instead of using a `HashSet<Key>`.
    - If not, and if you are going to have too many keys in the `HashSet<Key>` to fit in the memory, you will need to use a disk-based key-value store such as [RocksDB](https://rocksdb.org/).

If you can tolerates some errors, e.g. allow ~0.01% of unique keys might never appear, you could use a probabilistic data structure such as [Bloom filter](https://en.wikipedia.org/wiki/Bloom_filter) instead of `HashSet<Key>`.

- These data structures are space-efficient; they use very small amount of memory, compared to `HashSet<Key>`.
- However, Bloom filter, for example, allows false-positives; it can answer a given key is a member of it when it is actually not.
    - You can reduce the rate of false-positives by giving more space (memory) to the Bloom filter.

It will be much easier if you never get duplicate items. So please tell me why you will get duplicate items and maybe I can come up with a way to avoid them.

**Comment by Threated** [comment]
Ok let me give you a bit of code:
```rust
struct StreamingMap<T> {
    new_items: tokio::sync::broadcast::Sender<Arc<T>>,
    stored_items: moka::future::Cache<String, Arc<T>>
}

impl<T> StreamingMap<T> {
    async fn insert(&self, v: T) {
        let item = Arc::new(v);
        self.stored_items.insert(v.some_string_key.clone(), v.clone()).await;
        self.new_items.send(v);
    }

    fn stream_n_elements(&self, n: usize) -> impl Stream<Item = Arc<T>> {
        // If I subscribe before I might get elements which got inserted into the Cache and the channel
        let new_items = self.new_items.subscribe();
        let stored_tasks = self.stored_items.iter().map(|v| v.1).collect();
        // If I subscribe here I might miss a task which was inserted during iteration of the cache
        stream::iter(stored_tasks).chain(tokio_stream::wrappers::BroadcastStrean::new(new_items)).take(n)
    }
}
```

Both of these race conditions are pretty rare and only happen in my tokio::test(flavor = "multi_thread") in about 20% of the cases when I race the insert against reading one element from the stream.
Thats why I dont really want to create a HashSet just for that or similar for that case but maybe I have to.
I was also thinking about subscribing to the channel twice one time before and one time after storing the elements and check the first channel until it "reaches" the element of the second channel but it also seems complicated.

**Comment by tatsuya6502** [comment]
Thanks! Now I got a clear picture.

Unfortunately, as of `moka@v0.12.3`, you will need to dedup because:

1. As you said, it is not reliable to control the timing by calling `subscribe` of the channel.
2. `future::Cache`'s iterator does not guarantee to return an entry if its key has been inserted to the cache _after_ the iterator was created. ([doc](https://docs.rs/moka/0.12.3/moka/future/struct.Cache.html#method.iter))
    - If an entry is not returned from the cache's iterator, you need to get it from the channel instead.
    - This means, you must subscribe the channel first, and then call the `iter` method of the cache.

Also please note that the iterator from `self.stored_items.iter()` returns items in _arbitrary (random) order_, not the insertion order. ([doc](https://docs.rs/moka/0.12.3/moka/future/struct.Cache.html#method.iter))

> Creates an iterator visiting all key-value pairs in arbitrary order.

This is a common behavior from hash tables. Here is the [doc](https://doc.rust-lang.org/stable/std/collections/struct.HashMap.html#method.iter) of `std::collections::HashMap`: 

> An iterator visiting all key-value pairs in arbitrary order.

* * *

Here is one way to dedup using timestamps. It also sorts the items from the cache by the timestamp (= the insertion order):

In your `insert` method:

1. Store the current timestamp (`std::time::Instant`) to both the items for the cache and channel.

In your `stream_n_elements` method:

1. Subscribe the channel.
2. Get the current timestamp and set it to a variable `ts`.
3. Create an iterator of the cache, filter (keep) the items with timestamp `<= ts`, and collect them into a `Vec`.
4. Sort the items in the `Vec` by their timestamps (older to newer).
5. Wrap the stream from the channel by `skip_while` of `StreamExt` with the condition `item.timestamp <= ts`.
6. Chain the stream from the `Vec` and the stream from the channel.

* * *

I know above is a bit silly to do. Maybe we need `Cache` to do it for us; it should provide async steams or something that return all cached items in the insertion order.

**Comment by Threated** [comment]
It worked thank you very much.
Initially I was inserting the same timestamp into the channel and the cache which obviously did not work but after I changed it my tests finally passed. 🎉
